### PR TITLE
Implement mica

### PR DESCRIPTION
**Pull request by MishaTY**
- Implement mica for file explorer

### CODE REVIEW

**Comment by valinet** [comment]
Hi

Thanks for backporting this.

2 mentions:

* CheckIfBuild22523OrHigher is redundant, in that there already is VnGetOSVersion and that could be used instead to get the build number. Or global_rovi which caches that.
* It’s interesting: so Mica in 22523+ requires value=2 instead of 1 when setting attribute 1029. Again, there is a define for that, but nevertheless, I should account for that throughout the whole code, right? Does Mica work for the Properties window in 22523+?

**Comment by MishaTY** [comment]
Mica in 22523+ requires a value of 2 because the defintion was changed. Before that build it was a simple true/false value, but now it is like this:
```
DWMSBT_AUTO = 0,
DWMSBT_DISABLE = 1, // None
DWMSBT_MAINWINDOW = 2, // Mica
DWMSBT_TRANSIENTWINDOW = 3, // Acrylic
DWMSBT_TABBEDWINDOW = 4 // Tabbed
```
Not sure what you mean by will it work in the properties window.

**Comment by valinet** [comment]
> Not sure what you mean by will it work in the properties window.

Properties window has Mica. I was curious if it works in build 22523+ since I set it with 1. Probably not. Never mind. Yeah, I will modify the rest of the checks in the program too to account for that. So Acrylic is now achieved with that instead of the old, hacky way with `SetWindowCompositionAttribute`. A welcome change, I guess, a unified API is better.

**Comment by valinet** [comment]
Do you mind if I merge it manually?

**Comment by MishaTY** [comment]
I don't mind

**Comment by valinet** [comment]
"Simplify logic" was what I was going to suggest. Anyway, I modified the global utilities `IsWindows11`, `IsDwmExtendFrameIntoClientAreaBrokenInThisBuild`, `IsMicaMaterialSupportedInThisBuild` to use a global `RTL_OSVERSIONINFOW` structure in order to speed them up a bit, as they are called very frequently, so that's why I want to merge manually, the changes are not yet upstreamed.

**Comment by valinet** [comment]
Is `DWMExtendFrameHook` really required? Seems to work without.

**Comment by MishaTY** [comment]
It is required, as the window will flicker when resizing

**Comment by valinet** [comment]
Okay, implemented this in the latest commits. Will close this for now, thanks for the help.

**Pull request closed without merging**
