### PR TITLE
window commit

### PR DESCRIPTION
**Pull request by NT-Soft**
adding a window that show hello

### CODE REVIEW

**Comment by pyrates999** [comment]
why is this needed?

**Comment by pyrates999** [comment]
probably malicious code since it's in assembly

**Comment by NT-Soft** [comment]
Can i use explorer patcher reg tweak to create like a second version in console style in C#?

**Comment by NT-Soft** [comment]
And also i forget that file was for a os. So exuse me for that file. You can reject it

**Pull request closed without merging**
