### PR TITLE
Use GITHUB_TOKEN instead of PAT for forks, and upload new build result only for push done on master branch

### PR DESCRIPTION
**Pull request by BraINstinct0**
1) GITHUB_TOKEN is created on virtual env startup(for Actions), used , and destroyed, reducing possibility of PAT leak. So it is better for security.
2) Even when the repo is forked the build will work, so it'll reduce steps for manual edit&compile.

### CODE REVIEW

**Comment by valinet** [comment]
I specifically used my token so that the generated builds appear under my name instead of “GitHub Actions”. For the moment, I want that, I think it looks better, gives a better feel for the users.

The solution to have it work in forks is maybe an if check when deciding which token to use: PAT for my repo, GITHUB_TOKEN for the rest.

Please revise this to incorporate that.

Thanks

**Comment by BraINstinct0** [comment]
Will do.
TO DO
1. Check if `github.event_name`==`pull`
if True, 2-1. Check if `github.repository`==`valinet/ExplorerPatcher`. if True, use secrets.PAT. if False, use secrets.GITHUB_TOKEN.
if False, 2-2. disable uploading build artifact to the Releases, and just use `secrets.GITHUB_TOKEN`

does this seem reasonable?

**Comment by valinet** [comment]
I don’t understand exactly.

**Comment by BraINstinct0** [comment]
Sorry, I'll try to state it more clearly.
1. `pull_request` trigger the workflow in the current status, but it shouldn't be uploaded to Release.
2. If build was triggered by `push` a new build should be uploaded to Release.
+
3. If the workflow was triggered within your repo, `secrets.PAT` should be used.
4. If not(so, if it's from a fork), `secrets.GITHUB_TOKEN` can be used.(as you stated above)

**Comment by valinet** [comment]
Yeah, exactly, that’s fine.

**Comment by BraINstinct0** [comment]
Done.

However as the edited title says, it will, and always will, result in uploading a new build to the release whenever a push is done to the main branch. So be aware, (for example) if you merge this PR on GitHub, it'll make a new build and upload it if successful.

One possibly annoying effect is that 'checks'(which are, currently, just trying to build without uploading it) will be done for every PR(and PR updates). Those can be seen at your repo's actions tab. At least I've (I think) blocked it causing any release by itself.

**Comment by BraINstinct0** [comment]
Example of run done on master branch of a fork : https://github.com/BraINstinct0/ExplorerPatcher/runs/4234838007

**Comment by valinet** [comment]
Thanks. I know about it running for every push, it's what is done now as well.

I will review it and probably merge it manually as I want to do some other changes as well... for example, I think having it output builds as pre-releases and only upload to releases when the commit name is prefixed with something is better. That way, I can decide when to push an update to the general public, while also having builds generated for each commit, so interested people can test.

**Comment by valinet** [comment]
I just have to think about this for a while, I understand the issues, we will have a fix eventually in the upstream as well. It's because of this I haven't yet pushed the window switcher changes yet, it indeed makes it harder to push stuff since you have to remember to go cancel the run etc. I will fix this, no doubt.

**Comment by BraINstinct0** [comment]
Will leave this PR open for now, good to hear about the plans

**Comment by valinet** [comment]
Okay, thank you again for taking the time.

**Comment by valinet** [comment]
Manually implemented. Thanks.

**Pull request closed without merging**
