### PR TITLE
EP having issues with Latest stable version 22621.2134 and Fixing Wi-Fi Flyout buttons

### PR DESCRIPTION
**Pull request by Vipin2003**
Hello @valinet, firstly **SORRY🙏🙏** for tagging you. But EP is currently not working properly with the latest stable builds i.e. 22621.2134. There are so many bugs occuring with EP in 2134. List of bugs are :

1. **Action Center Overlapping** : With latest build, notification or action center is overlapping over taskbar in Win10 Taskbar style
2023-08-12_15h19_15

2. **Classic R-Click not accessible** : the classic R-click menu, which you have implemented for Win11 Taskbar, is not working anymore. If we try to access it, explorer crashes. _No Screenshot as explorer crashes._

3. **Start Folders not working** : Other buttons near Power buttons are not working anymore. We are not able to customize them.
2023-08-12_09h12_24

If it is possible, then please fix these bugs by bumping ExplorerPatcher.
---------------------------------------------------------------------------------------------------------------------------------
**(optional)** Fix for Broken Win10 Wi-Fi buttons : (steps)
1. Navigate to `C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy`
2. Find and Rename the file named **dxgi.dll** to **dxgi.bak**
3. Restart the explorer.

It will Fix the Windows 10 Wi-Fi Flyout buttons completely.

### CODE REVIEW

**Comment by GentlemanMC** [comment]
when merge?

**Comment by valinet** [comment]
@Vipin2003 Man, what’s the point of this commit? I don’t see any code to help fix the issues, just reiterating issues, although this is in the PR section, with 2 commits that overlap one another, do not respect the naming scheme that’s clearly identifiable by looking on past commits, basically pure SPAM.

It’s getting on my nerves. Posting once is enough. I don’t have a duty to fix anything neither to you, nor to anyone. I kind of understand opening a million issues on the same topic, the occasional tagging and so on, but to tag me in a useless PR is too much, just shows utter disrespect and entitlement.

My 2 cents for this crap.

**Comment by Vipin2003** [comment]
Ahh...sorry. I just pasted my issue to PR....Forgot that I've to find a solution for this first.

**Comment by valinet** [comment]
Nah, you did not forget anything... At least own your actions, don't try to come up with lame excuses - it's plenty clear how Git works. Again, my 2 cents...

**Comment by Daisyfan1995** [comment]
Need new build version?

**Pull request closed without merging**
