### PR TITLE
Update windows-2022 -> windows-2025, Do not persist credentials

### PR DESCRIPTION
**Pull request by Kichura**
Updates the CI's OS image from Windows Server 2022 -> Windows Server 2025 basically, also credentials will not be persisted through checkouts which is to prevent exposing workflow to greater risks than imagined.

### CODE REVIEW

**Comment by pyrates999** [comment]
This software is not for the server versions of windows.

**Comment by Kichura** [comment]
> This software is not for the server versions of windows.

i am aware of this. this is meant for compiling the software through github actions and that explorerpatcher mainly focuses on windows 11 itself nowadays.

**Comment by Kichura** [comment]
Ready for review as `windows-2025` is now available.

**Comment by Kichura** [comment]
Cancelled because amr doesn't wanna touch on EP code anymore due to windhawk and stated my PR isn't important. *(will not make anymore talks in this repo)*

**Pull request closed without merging**
