### PR TITLE
Compatibility with a few other taskbar things

### PR DESCRIPTION
**Pull request by TheGamer1002**

### CODE REVIEW

**Comment by Anixx** [comment]
There is no compatibility with OpenShell out of the box when using Classic theme. One has to install a patched OpenShell DLL, otherwise the things get broken.

**Comment by valinet** [comment]
I don’t think this necessarily has to live in the README. I can add those mentions *somewhere* in the wiki where it is easier to edit and a more verbose description can be added, including how it works alongside various programs under certain configurations. That some people skip the wiki and even the README, yeah, idk, they shouldn’t.

**Comment by TheGamer1002** [comment]
> There is no compatibility with OpenShell out of the box when using Classic theme. One has to install a patched OpenShell DLL, otherwise the things get broken.

Really? Interesting! I installed ExplorerPatcher, changed to the Windows 10 taskbar, and then installed OpenShell and it worked just fine. It could just be that my installation is already heavily modified, but Windows 11 (at least) works straight out of the box.

> I don’t think this necessarily has to live in the README. I can add those mentions somewhere in the wiki where it is easier to edit and a more verbose description can be added, including how it works alongside various programs under certain configurations.

That’s fine by me. The more apps, the better.

> That some people skip the wiki and even the README, yeah, idk, they shouldn’t.

Agree :P. Perhaps a link in the readme to the wiki for a full list of features.

**Comment by TheGamer1002** [comment]
Just looked and there’s already a link! Cool!

**Comment by valinet** [comment]
He speaks about classic theme as in enabling the Windows 95 theme on Windows 11 and then how OpenShell needs a patched DLL to fully work alongside ExplorerPatcher.

**Comment by TheGamer1002** [comment]
> He speaks about classic theme as in enabling the Windows 95 theme on Windows 11 and then how OpenShell needs a patched DLL to fully work alongside ExplorerPatcher.

Ok, I understand now! I (unsuccessfully) tried to get the Windows 95 theme working. Still a bit confused by the Open Shell thing but I now understand additional configuration is needed for it.

**Comment by valinet** [comment]
Not necessarily, the patched DLL allows applying a texture to the taskbar so that it displays properly and along with EP’s classic theme mitigations the thing works fine in that configuration too, being easily daily drivable, not requiring a third party taskbar.

**Comment by valinet** [comment]
A tutorial for classic theme under Windows 11 is available here: https://github.com/valinet/ExplorerPatcher/discussions/167

**Comment by TheGamer1002** [comment]
Alright. Shall we close this PR? I can’t edit the wiki page.

**Comment by TheGamer1002** [comment]
Ok, a patched DLL is needed for the classic theme. Maybe I’ll make a simple app that’ll install the needed things for the classic theme from the command lime.

**Pull request closed without merging**
