### PR TITLE
Add issue forms to repository

### PR DESCRIPTION
**Pull request by Poopooracoocoo**
Feedback welcome. Feel free to decline or make any changes :)

Screenshots:
image
image

Please squash if merged

### CODE REVIEW

**Comment by valinet** [comment]
@Amrsatrio Any feedback on this? I kind of like it, tempted to merge :D

**Comment by pyrates999** [comment]
I think this is great!

**Comment by Poopooracoocoo** [comment]
Thought of something... The idea is to use the General category for support and the Q&A category for questions. I've also thought about adding a bit of text on the top - that I doubt anyone would read

Let me know if this is something I should push
image
image

**Comment by pyrates999** [comment]
I think the following fields would be helpful and require them to be filled in:

1. Windows version (10 or 11)
2. Windows version and build number, indicate they can get it from running the command winver (22621.2283)
4. EP version, indicate they can find it by opening the EP properties application and going to the about section on the left side
5. Indicate if EP version installed is a release or pre-release
6. steps to recreate bug
7. what actually happens
8. what you expect to happen
9. screen shots of settings you changed in the EP properties application

**Comment by creeper-0910** [comment]
The registry may be causing the problem, so (not a good way to go) you may need a check box to see if you have deleted the EP registry.

**Pull request closed without merging**
